sudo: required
services:
  - docker
env: SH="docker exec -t container bash -c"

git:
  depth: false

cache:
  directories:
  - docker_images

before_install:
  - docker load -i docker_images/images.tar || true
  - docker run -d --name container -v $(pwd):/travis -w /travis yaqwsx/rofi tail -f /dev/null
  - docker ps

before_cache:
  - docker save -o docker_images/images.tar $(docker images -a -q)

script:
  - $SH "make all.gcc"
  - $SH "make all.clang"
  - $SH "make test.gcc"
  - $SH "make test.clang"
  # Fetch all git branches before building documentation
  - git branch -r | grep -v '\->' | while read remote; do git branch --track "${remote#origin/}" "$remote"; done
  - git checkout master # Build the master documentation
  - git fetch --all
  - git pull --all
  - $SH "cd doc; make -j3"
  - $SH "releng/doc/buildDevDoc.sh"
  - sudo cp -r _build.doc/branch doc/build/html # Sudo is there because of the docker privileges

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: doc/build/html
  keep_history: false
